### ISSUE TITLE
Name display after "register" action

### ISSUE THREAD

**Issue by NilesDev** [erik78se/charm-gitlab-runner#6]
Unregistering and registering a runner works, but the Message afterward is "Ready (Registered OK)" instead of "Ready (\<name\>)".

**Comment by NilesDev** [comment]
The runner also loses the setting for picking up un-tagged jobs, but that might only be stored in Gitlab in the first place.

**Comment by erik78se** [comment]
Commen: The settings are not lost. Its just that this feature works differently now. Registering a runner with tag-list="" causes the charm to pick up untagged jobs.

**Comment by erik78se** [comment]
The messaging is however something I'll fix.

**Comment by erik78se** [comment]
Done
